name: Deploy

on: 
  push:
    tags:
      - '*'

jobs:
  release:
    name: Publish to Docker registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_REGISTRY }}/ggwp/${{ github.event.repository.name }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
          # always generate latest tag on push
          flavor: |
            latest=true

      - name: Build and push to Docker registry
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}